all: true
dir: '{{.InterfaceDir}}/{{.SrcPackageName}}_mocks'
structname: '{{.InterfaceName}}'
pkgname: '{{.SrcPackageName}}_mocks'
filename: "{{.SrcPackageName}}_gen.go"
template: testify
template-data:
  unroll-variadic: true
packages:
  github.com/Radiushina/loyalty-system/internal/order:
    config:
      recursive: true
