// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package order_mocks

import (
	"context"

	"github.com/Radiushina/loyalty-system/internal/order"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewServiceProvider creates a new instance of ServiceProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServiceProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *ServiceProvider {
	mock := &ServiceProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ServiceProvider is an autogenerated mock type for the ServiceProvider type
type ServiceProvider struct {
	mock.Mock
}

type ServiceProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *ServiceProvider) EXPECT() *ServiceProvider_Expecter {
	return &ServiceProvider_Expecter{mock: &_m.Mock}
}

// CreateOrder provides a mock function for the type ServiceProvider
func (_mock *ServiceProvider) CreateOrder(ctx context.Context, userID uuid.UUID, orderNumber string) error {
	ret := _mock.Called(ctx, userID, orderNumber)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = returnFunc(ctx, userID, orderNumber)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ServiceProvider_CreateOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrder'
type ServiceProvider_CreateOrder_Call struct {
	*mock.Call
}

// CreateOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - orderNumber string
func (_e *ServiceProvider_Expecter) CreateOrder(ctx interface{}, userID interface{}, orderNumber interface{}) *ServiceProvider_CreateOrder_Call {
	return &ServiceProvider_CreateOrder_Call{Call: _e.mock.On("CreateOrder", ctx, userID, orderNumber)}
}

func (_c *ServiceProvider_CreateOrder_Call) Run(run func(ctx context.Context, userID uuid.UUID, orderNumber string)) *ServiceProvider_CreateOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ServiceProvider_CreateOrder_Call) Return(err error) *ServiceProvider_CreateOrder_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ServiceProvider_CreateOrder_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, orderNumber string) error) *ServiceProvider_CreateOrder_Call {
	_c.Call.Return(run)
	return _c
}

// SelectOrders provides a mock function for the type ServiceProvider
func (_mock *ServiceProvider) SelectOrders(ctx context.Context, userID uuid.UUID) ([]order.Order, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for SelectOrders")
	}

	var r0 []order.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]order.Order, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []order.Order); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]order.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ServiceProvider_SelectOrders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SelectOrders'
type ServiceProvider_SelectOrders_Call struct {
	*mock.Call
}

// SelectOrders is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *ServiceProvider_Expecter) SelectOrders(ctx interface{}, userID interface{}) *ServiceProvider_SelectOrders_Call {
	return &ServiceProvider_SelectOrders_Call{Call: _e.mock.On("SelectOrders", ctx, userID)}
}

func (_c *ServiceProvider_SelectOrders_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *ServiceProvider_SelectOrders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ServiceProvider_SelectOrders_Call) Return(orders []order.Order, err error) *ServiceProvider_SelectOrders_Call {
	_c.Call.Return(orders, err)
	return _c
}

func (_c *ServiceProvider_SelectOrders_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) ([]order.Order, error)) *ServiceProvider_SelectOrders_Call {
	_c.Call.Return(run)
	return _c
}

// NewRepoProvider creates a new instance of RepoProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepoProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *RepoProvider {
	mock := &RepoProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// RepoProvider is an autogenerated mock type for the RepoProvider type
type RepoProvider struct {
	mock.Mock
}

type RepoProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *RepoProvider) EXPECT() *RepoProvider_Expecter {
	return &RepoProvider_Expecter{mock: &_m.Mock}
}

// InsertOrder provides a mock function for the type RepoProvider
func (_mock *RepoProvider) InsertOrder(ctx context.Context, userID uuid.UUID, orderNumber string) (uuid.UUID, error) {
	ret := _mock.Called(ctx, userID, orderNumber)

	if len(ret) == 0 {
		panic("no return value specified for InsertOrder")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (uuid.UUID, error)); ok {
		return returnFunc(ctx, userID, orderNumber)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) uuid.UUID); ok {
		r0 = returnFunc(ctx, userID, orderNumber)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = returnFunc(ctx, userID, orderNumber)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RepoProvider_InsertOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertOrder'
type RepoProvider_InsertOrder_Call struct {
	*mock.Call
}

// InsertOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - orderNumber string
func (_e *RepoProvider_Expecter) InsertOrder(ctx interface{}, userID interface{}, orderNumber interface{}) *RepoProvider_InsertOrder_Call {
	return &RepoProvider_InsertOrder_Call{Call: _e.mock.On("InsertOrder", ctx, userID, orderNumber)}
}

func (_c *RepoProvider_InsertOrder_Call) Run(run func(ctx context.Context, userID uuid.UUID, orderNumber string)) *RepoProvider_InsertOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *RepoProvider_InsertOrder_Call) Return(uUID uuid.UUID, err error) *RepoProvider_InsertOrder_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *RepoProvider_InsertOrder_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, orderNumber string) (uuid.UUID, error)) *RepoProvider_InsertOrder_Call {
	_c.Call.Return(run)
	return _c
}

// SelectOrders provides a mock function for the type RepoProvider
func (_mock *RepoProvider) SelectOrders(ctx context.Context, userID uuid.UUID) ([]order.Order, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for SelectOrders")
	}

	var r0 []order.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]order.Order, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []order.Order); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]order.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RepoProvider_SelectOrders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SelectOrders'
type RepoProvider_SelectOrders_Call struct {
	*mock.Call
}

// SelectOrders is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *RepoProvider_Expecter) SelectOrders(ctx interface{}, userID interface{}) *RepoProvider_SelectOrders_Call {
	return &RepoProvider_SelectOrders_Call{Call: _e.mock.On("SelectOrders", ctx, userID)}
}

func (_c *RepoProvider_SelectOrders_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *RepoProvider_SelectOrders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RepoProvider_SelectOrders_Call) Return(orders []order.Order, err error) *RepoProvider_SelectOrders_Call {
	_c.Call.Return(orders, err)
	return _c
}

func (_c *RepoProvider_SelectOrders_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) ([]order.Order, error)) *RepoProvider_SelectOrders_Call {
	_c.Call.Return(run)
	return _c
}

// NewAccrualEnqueuer creates a new instance of AccrualEnqueuer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAccrualEnqueuer(t interface {
	mock.TestingT
	Cleanup(func())
}) *AccrualEnqueuer {
	mock := &AccrualEnqueuer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AccrualEnqueuer is an autogenerated mock type for the AccrualEnqueuer type
type AccrualEnqueuer struct {
	mock.Mock
}

type AccrualEnqueuer_Expecter struct {
	mock *mock.Mock
}

func (_m *AccrualEnqueuer) EXPECT() *AccrualEnqueuer_Expecter {
	return &AccrualEnqueuer_Expecter{mock: &_m.Mock}
}

// Enqueue provides a mock function for the type AccrualEnqueuer
func (_mock *AccrualEnqueuer) Enqueue(job order.OrderJob) {
	_mock.Called(job)
	return
}

// AccrualEnqueuer_Enqueue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Enqueue'
type AccrualEnqueuer_Enqueue_Call struct {
	*mock.Call
}

// Enqueue is a helper method to define mock.On call
//   - job order.OrderJob
func (_e *AccrualEnqueuer_Expecter) Enqueue(job interface{}) *AccrualEnqueuer_Enqueue_Call {
	return &AccrualEnqueuer_Enqueue_Call{Call: _e.mock.On("Enqueue", job)}
}

func (_c *AccrualEnqueuer_Enqueue_Call) Run(run func(job order.OrderJob)) *AccrualEnqueuer_Enqueue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 order.OrderJob
		if args[0] != nil {
			arg0 = args[0].(order.OrderJob)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *AccrualEnqueuer_Enqueue_Call) Return() *AccrualEnqueuer_Enqueue_Call {
	_c.Call.Return()
	return _c
}

func (_c *AccrualEnqueuer_Enqueue_Call) RunAndReturn(run func(job order.OrderJob)) *AccrualEnqueuer_Enqueue_Call {
	_c.Run(run)
	return _c
}

// NewWorkerRepoProvider creates a new instance of WorkerRepoProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWorkerRepoProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *WorkerRepoProvider {
	mock := &WorkerRepoProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// WorkerRepoProvider is an autogenerated mock type for the WorkerRepoProvider type
type WorkerRepoProvider struct {
	mock.Mock
}

type WorkerRepoProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *WorkerRepoProvider) EXPECT() *WorkerRepoProvider_Expecter {
	return &WorkerRepoProvider_Expecter{mock: &_m.Mock}
}

// GetOrderByID provides a mock function for the type WorkerRepoProvider
func (_mock *WorkerRepoProvider) GetOrderByID(ctx context.Context, orderID uuid.UUID) (order.Order, error) {
	ret := _mock.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrderByID")
	}

	var r0 order.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (order.Order, error)); ok {
		return returnFunc(ctx, orderID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) order.Order); ok {
		r0 = returnFunc(ctx, orderID)
	} else {
		r0 = ret.Get(0).(order.Order)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, orderID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// WorkerRepoProvider_GetOrderByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrderByID'
type WorkerRepoProvider_GetOrderByID_Call struct {
	*mock.Call
}

// GetOrderByID is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID uuid.UUID
func (_e *WorkerRepoProvider_Expecter) GetOrderByID(ctx interface{}, orderID interface{}) *WorkerRepoProvider_GetOrderByID_Call {
	return &WorkerRepoProvider_GetOrderByID_Call{Call: _e.mock.On("GetOrderByID", ctx, orderID)}
}

func (_c *WorkerRepoProvider_GetOrderByID_Call) Run(run func(ctx context.Context, orderID uuid.UUID)) *WorkerRepoProvider_GetOrderByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *WorkerRepoProvider_GetOrderByID_Call) Return(order1 order.Order, err error) *WorkerRepoProvider_GetOrderByID_Call {
	_c.Call.Return(order1, err)
	return _c
}

func (_c *WorkerRepoProvider_GetOrderByID_Call) RunAndReturn(run func(ctx context.Context, orderID uuid.UUID) (order.Order, error)) *WorkerRepoProvider_GetOrderByID_Call {
	_c.Call.Return(run)
	return _c
}

// SelectPendingOrders provides a mock function for the type WorkerRepoProvider
func (_mock *WorkerRepoProvider) SelectPendingOrders(ctx context.Context, limit int) ([]order.Order, error) {
	ret := _mock.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for SelectPendingOrders")
	}

	var r0 []order.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]order.Order, error)); ok {
		return returnFunc(ctx, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []order.Order); ok {
		r0 = returnFunc(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]order.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// WorkerRepoProvider_SelectPendingOrders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SelectPendingOrders'
type WorkerRepoProvider_SelectPendingOrders_Call struct {
	*mock.Call
}

// SelectPendingOrders is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
func (_e *WorkerRepoProvider_Expecter) SelectPendingOrders(ctx interface{}, limit interface{}) *WorkerRepoProvider_SelectPendingOrders_Call {
	return &WorkerRepoProvider_SelectPendingOrders_Call{Call: _e.mock.On("SelectPendingOrders", ctx, limit)}
}

func (_c *WorkerRepoProvider_SelectPendingOrders_Call) Run(run func(ctx context.Context, limit int)) *WorkerRepoProvider_SelectPendingOrders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *WorkerRepoProvider_SelectPendingOrders_Call) Return(orders []order.Order, err error) *WorkerRepoProvider_SelectPendingOrders_Call {
	_c.Call.Return(orders, err)
	return _c
}

func (_c *WorkerRepoProvider_SelectPendingOrders_Call) RunAndReturn(run func(ctx context.Context, limit int) ([]order.Order, error)) *WorkerRepoProvider_SelectPendingOrders_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateOrderAccrual provides a mock function for the type WorkerRepoProvider
func (_mock *WorkerRepoProvider) UpdateOrderAccrual(ctx context.Context, orderID uuid.UUID, status order.Status, accrual int) error {
	ret := _mock.Called(ctx, orderID, status, accrual)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrderAccrual")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, order.Status, int) error); ok {
		r0 = returnFunc(ctx, orderID, status, accrual)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// WorkerRepoProvider_UpdateOrderAccrual_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOrderAccrual'
type WorkerRepoProvider_UpdateOrderAccrual_Call struct {
	*mock.Call
}

// UpdateOrderAccrual is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID uuid.UUID
//   - status order.Status
//   - accrual int
func (_e *WorkerRepoProvider_Expecter) UpdateOrderAccrual(ctx interface{}, orderID interface{}, status interface{}, accrual interface{}) *WorkerRepoProvider_UpdateOrderAccrual_Call {
	return &WorkerRepoProvider_UpdateOrderAccrual_Call{Call: _e.mock.On("UpdateOrderAccrual", ctx, orderID, status, accrual)}
}

func (_c *WorkerRepoProvider_UpdateOrderAccrual_Call) Run(run func(ctx context.Context, orderID uuid.UUID, status order.Status, accrual int)) *WorkerRepoProvider_UpdateOrderAccrual_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 order.Status
		if args[2] != nil {
			arg2 = args[2].(order.Status)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *WorkerRepoProvider_UpdateOrderAccrual_Call) Return(err error) *WorkerRepoProvider_UpdateOrderAccrual_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *WorkerRepoProvider_UpdateOrderAccrual_Call) RunAndReturn(run func(ctx context.Context, orderID uuid.UUID, status order.Status, accrual int) error) *WorkerRepoProvider_UpdateOrderAccrual_Call {
	_c.Call.Return(run)
	return _c
}

// NewBalanceProvider creates a new instance of BalanceProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBalanceProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *BalanceProvider {
	mock := &BalanceProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// BalanceProvider is an autogenerated mock type for the BalanceProvider type
type BalanceProvider struct {
	mock.Mock
}

type BalanceProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *BalanceProvider) EXPECT() *BalanceProvider_Expecter {
	return &BalanceProvider_Expecter{mock: &_m.Mock}
}

// CreditAccrual provides a mock function for the type BalanceProvider
func (_mock *BalanceProvider) CreditAccrual(ctx context.Context, userID uuid.UUID, orderID uuid.UUID, amount int) error {
	ret := _mock.Called(ctx, userID, orderID, amount)

	if len(ret) == 0 {
		panic("no return value specified for CreditAccrual")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, int) error); ok {
		r0 = returnFunc(ctx, userID, orderID, amount)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// BalanceProvider_CreditAccrual_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreditAccrual'
type BalanceProvider_CreditAccrual_Call struct {
	*mock.Call
}

// CreditAccrual is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - orderID uuid.UUID
//   - amount int
func (_e *BalanceProvider_Expecter) CreditAccrual(ctx interface{}, userID interface{}, orderID interface{}, amount interface{}) *BalanceProvider_CreditAccrual_Call {
	return &BalanceProvider_CreditAccrual_Call{Call: _e.mock.On("CreditAccrual", ctx, userID, orderID, amount)}
}

func (_c *BalanceProvider_CreditAccrual_Call) Run(run func(ctx context.Context, userID uuid.UUID, orderID uuid.UUID, amount int)) *BalanceProvider_CreditAccrual_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *BalanceProvider_CreditAccrual_Call) Return(err error) *BalanceProvider_CreditAccrual_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *BalanceProvider_CreditAccrual_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, orderID uuid.UUID, amount int) error) *BalanceProvider_CreditAccrual_Call {
	_c.Call.Return(run)
	return _c
}
