// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package order_mocks

import (
	"context"

	"github.com/Radiushina/loyalty-system/internal/order"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewServiceProvider creates a new instance of ServiceProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServiceProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *ServiceProvider {
	mock := &ServiceProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ServiceProvider is an autogenerated mock type for the ServiceProvider type
type ServiceProvider struct {
	mock.Mock
}

type ServiceProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *ServiceProvider) EXPECT() *ServiceProvider_Expecter {
	return &ServiceProvider_Expecter{mock: &_m.Mock}
}

// CreateOrder provides a mock function for the type ServiceProvider
func (_mock *ServiceProvider) CreateOrder(ctx context.Context, userID uuid.UUID, orderNumber string) error {
	ret := _mock.Called(ctx, userID, orderNumber)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = returnFunc(ctx, userID, orderNumber)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ServiceProvider_CreateOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrder'
type ServiceProvider_CreateOrder_Call struct {
	*mock.Call
}

// CreateOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - orderNumber string
func (_e *ServiceProvider_Expecter) CreateOrder(ctx interface{}, userID interface{}, orderNumber interface{}) *ServiceProvider_CreateOrder_Call {
	return &ServiceProvider_CreateOrder_Call{Call: _e.mock.On("CreateOrder", ctx, userID, orderNumber)}
}

func (_c *ServiceProvider_CreateOrder_Call) Run(run func(ctx context.Context, userID uuid.UUID, orderNumber string)) *ServiceProvider_CreateOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ServiceProvider_CreateOrder_Call) Return(err error) *ServiceProvider_CreateOrder_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ServiceProvider_CreateOrder_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, orderNumber string) error) *ServiceProvider_CreateOrder_Call {
	_c.Call.Return(run)
	return _c
}

// SelectOrders provides a mock function for the type ServiceProvider
func (_mock *ServiceProvider) SelectOrders(ctx context.Context, userID uuid.UUID) ([]order.Order, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for SelectOrders")
	}

	var r0 []order.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]order.Order, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []order.Order); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]order.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ServiceProvider_SelectOrders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SelectOrders'
type ServiceProvider_SelectOrders_Call struct {
	*mock.Call
}

// SelectOrders is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *ServiceProvider_Expecter) SelectOrders(ctx interface{}, userID interface{}) *ServiceProvider_SelectOrders_Call {
	return &ServiceProvider_SelectOrders_Call{Call: _e.mock.On("SelectOrders", ctx, userID)}
}

func (_c *ServiceProvider_SelectOrders_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *ServiceProvider_SelectOrders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ServiceProvider_SelectOrders_Call) Return(orders []order.Order, err error) *ServiceProvider_SelectOrders_Call {
	_c.Call.Return(orders, err)
	return _c
}

func (_c *ServiceProvider_SelectOrders_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) ([]order.Order, error)) *ServiceProvider_SelectOrders_Call {
	_c.Call.Return(run)
	return _c
}

// NewRepoProvider creates a new instance of RepoProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepoProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *RepoProvider {
	mock := &RepoProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// RepoProvider is an autogenerated mock type for the RepoProvider type
type RepoProvider struct {
	mock.Mock
}

type RepoProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *RepoProvider) EXPECT() *RepoProvider_Expecter {
	return &RepoProvider_Expecter{mock: &_m.Mock}
}

// InsertOrder provides a mock function for the type RepoProvider
func (_mock *RepoProvider) InsertOrder(ctx context.Context, userID uuid.UUID, orderNumber string) error {
	ret := _mock.Called(ctx, userID, orderNumber)

	if len(ret) == 0 {
		panic("no return value specified for InsertOrder")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = returnFunc(ctx, userID, orderNumber)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RepoProvider_InsertOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertOrder'
type RepoProvider_InsertOrder_Call struct {
	*mock.Call
}

// InsertOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - orderNumber string
func (_e *RepoProvider_Expecter) InsertOrder(ctx interface{}, userID interface{}, orderNumber interface{}) *RepoProvider_InsertOrder_Call {
	return &RepoProvider_InsertOrder_Call{Call: _e.mock.On("InsertOrder", ctx, userID, orderNumber)}
}

func (_c *RepoProvider_InsertOrder_Call) Run(run func(ctx context.Context, userID uuid.UUID, orderNumber string)) *RepoProvider_InsertOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *RepoProvider_InsertOrder_Call) Return(err error) *RepoProvider_InsertOrder_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RepoProvider_InsertOrder_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, orderNumber string) error) *RepoProvider_InsertOrder_Call {
	_c.Call.Return(run)
	return _c
}

// SelectOrders provides a mock function for the type RepoProvider
func (_mock *RepoProvider) SelectOrders(ctx context.Context, userID uuid.UUID) ([]order.Order, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for SelectOrders")
	}

	var r0 []order.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]order.Order, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []order.Order); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]order.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RepoProvider_SelectOrders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SelectOrders'
type RepoProvider_SelectOrders_Call struct {
	*mock.Call
}

// SelectOrders is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *RepoProvider_Expecter) SelectOrders(ctx interface{}, userID interface{}) *RepoProvider_SelectOrders_Call {
	return &RepoProvider_SelectOrders_Call{Call: _e.mock.On("SelectOrders", ctx, userID)}
}

func (_c *RepoProvider_SelectOrders_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *RepoProvider_SelectOrders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RepoProvider_SelectOrders_Call) Return(orders []order.Order, err error) *RepoProvider_SelectOrders_Call {
	_c.Call.Return(orders, err)
	return _c
}

func (_c *RepoProvider_SelectOrders_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) ([]order.Order, error)) *RepoProvider_SelectOrders_Call {
	_c.Call.Return(run)
	return _c
}
