// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package balance_mocks

import (
	"context"

	"github.com/Radiushina/loyalty-system/internal/balance"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewServiceProvider creates a new instance of ServiceProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServiceProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *ServiceProvider {
	mock := &ServiceProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ServiceProvider is an autogenerated mock type for the ServiceProvider type
type ServiceProvider struct {
	mock.Mock
}

type ServiceProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *ServiceProvider) EXPECT() *ServiceProvider_Expecter {
	return &ServiceProvider_Expecter{mock: &_m.Mock}
}

// SelectBalance provides a mock function for the type ServiceProvider
func (_mock *ServiceProvider) SelectBalance(ctx context.Context, userID uuid.UUID) (balance.UserBalance, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for SelectBalance")
	}

	var r0 balance.UserBalance
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (balance.UserBalance, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) balance.UserBalance); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(balance.UserBalance)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ServiceProvider_SelectBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SelectBalance'
type ServiceProvider_SelectBalance_Call struct {
	*mock.Call
}

// SelectBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *ServiceProvider_Expecter) SelectBalance(ctx interface{}, userID interface{}) *ServiceProvider_SelectBalance_Call {
	return &ServiceProvider_SelectBalance_Call{Call: _e.mock.On("SelectBalance", ctx, userID)}
}

func (_c *ServiceProvider_SelectBalance_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *ServiceProvider_SelectBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ServiceProvider_SelectBalance_Call) Return(userBalance balance.UserBalance, err error) *ServiceProvider_SelectBalance_Call {
	_c.Call.Return(userBalance, err)
	return _c
}

func (_c *ServiceProvider_SelectBalance_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) (balance.UserBalance, error)) *ServiceProvider_SelectBalance_Call {
	_c.Call.Return(run)
	return _c
}

// SelectWithdrawals provides a mock function for the type ServiceProvider
func (_mock *ServiceProvider) SelectWithdrawals(ctx context.Context, userID uuid.UUID) ([]balance.Withdrawal, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for SelectWithdrawals")
	}

	var r0 []balance.Withdrawal
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]balance.Withdrawal, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []balance.Withdrawal); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]balance.Withdrawal)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ServiceProvider_SelectWithdrawals_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SelectWithdrawals'
type ServiceProvider_SelectWithdrawals_Call struct {
	*mock.Call
}

// SelectWithdrawals is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *ServiceProvider_Expecter) SelectWithdrawals(ctx interface{}, userID interface{}) *ServiceProvider_SelectWithdrawals_Call {
	return &ServiceProvider_SelectWithdrawals_Call{Call: _e.mock.On("SelectWithdrawals", ctx, userID)}
}

func (_c *ServiceProvider_SelectWithdrawals_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *ServiceProvider_SelectWithdrawals_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ServiceProvider_SelectWithdrawals_Call) Return(withdrawals []balance.Withdrawal, err error) *ServiceProvider_SelectWithdrawals_Call {
	_c.Call.Return(withdrawals, err)
	return _c
}

func (_c *ServiceProvider_SelectWithdrawals_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) ([]balance.Withdrawal, error)) *ServiceProvider_SelectWithdrawals_Call {
	_c.Call.Return(run)
	return _c
}

// WithdrawBalance provides a mock function for the type ServiceProvider
func (_mock *ServiceProvider) WithdrawBalance(ctx context.Context, userID uuid.UUID, opt balance.WithdrawOpt) error {
	ret := _mock.Called(ctx, userID, opt)

	if len(ret) == 0 {
		panic("no return value specified for WithdrawBalance")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, balance.WithdrawOpt) error); ok {
		r0 = returnFunc(ctx, userID, opt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ServiceProvider_WithdrawBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithdrawBalance'
type ServiceProvider_WithdrawBalance_Call struct {
	*mock.Call
}

// WithdrawBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - opt balance.WithdrawOpt
func (_e *ServiceProvider_Expecter) WithdrawBalance(ctx interface{}, userID interface{}, opt interface{}) *ServiceProvider_WithdrawBalance_Call {
	return &ServiceProvider_WithdrawBalance_Call{Call: _e.mock.On("WithdrawBalance", ctx, userID, opt)}
}

func (_c *ServiceProvider_WithdrawBalance_Call) Run(run func(ctx context.Context, userID uuid.UUID, opt balance.WithdrawOpt)) *ServiceProvider_WithdrawBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 balance.WithdrawOpt
		if args[2] != nil {
			arg2 = args[2].(balance.WithdrawOpt)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ServiceProvider_WithdrawBalance_Call) Return(err error) *ServiceProvider_WithdrawBalance_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ServiceProvider_WithdrawBalance_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, opt balance.WithdrawOpt) error) *ServiceProvider_WithdrawBalance_Call {
	_c.Call.Return(run)
	return _c
}

// NewRepoProvider creates a new instance of RepoProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepoProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *RepoProvider {
	mock := &RepoProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// RepoProvider is an autogenerated mock type for the RepoProvider type
type RepoProvider struct {
	mock.Mock
}

type RepoProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *RepoProvider) EXPECT() *RepoProvider_Expecter {
	return &RepoProvider_Expecter{mock: &_m.Mock}
}

// CreditAccrual provides a mock function for the type RepoProvider
func (_mock *RepoProvider) CreditAccrual(ctx context.Context, userID uuid.UUID, orderID uuid.UUID, amount float64) error {
	ret := _mock.Called(ctx, userID, orderID, amount)

	if len(ret) == 0 {
		panic("no return value specified for CreditAccrual")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, float64) error); ok {
		r0 = returnFunc(ctx, userID, orderID, amount)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RepoProvider_CreditAccrual_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreditAccrual'
type RepoProvider_CreditAccrual_Call struct {
	*mock.Call
}

// CreditAccrual is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - orderID uuid.UUID
//   - amount float64
func (_e *RepoProvider_Expecter) CreditAccrual(ctx interface{}, userID interface{}, orderID interface{}, amount interface{}) *RepoProvider_CreditAccrual_Call {
	return &RepoProvider_CreditAccrual_Call{Call: _e.mock.On("CreditAccrual", ctx, userID, orderID, amount)}
}

func (_c *RepoProvider_CreditAccrual_Call) Run(run func(ctx context.Context, userID uuid.UUID, orderID uuid.UUID, amount float64)) *RepoProvider_CreditAccrual_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 float64
		if args[3] != nil {
			arg3 = args[3].(float64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *RepoProvider_CreditAccrual_Call) Return(err error) *RepoProvider_CreditAccrual_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RepoProvider_CreditAccrual_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, orderID uuid.UUID, amount float64) error) *RepoProvider_CreditAccrual_Call {
	_c.Call.Return(run)
	return _c
}

// SelectBalance provides a mock function for the type RepoProvider
func (_mock *RepoProvider) SelectBalance(ctx context.Context, userID uuid.UUID) (balance.UserBalance, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for SelectBalance")
	}

	var r0 balance.UserBalance
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (balance.UserBalance, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) balance.UserBalance); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(balance.UserBalance)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RepoProvider_SelectBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SelectBalance'
type RepoProvider_SelectBalance_Call struct {
	*mock.Call
}

// SelectBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *RepoProvider_Expecter) SelectBalance(ctx interface{}, userID interface{}) *RepoProvider_SelectBalance_Call {
	return &RepoProvider_SelectBalance_Call{Call: _e.mock.On("SelectBalance", ctx, userID)}
}

func (_c *RepoProvider_SelectBalance_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *RepoProvider_SelectBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RepoProvider_SelectBalance_Call) Return(userBalance balance.UserBalance, err error) *RepoProvider_SelectBalance_Call {
	_c.Call.Return(userBalance, err)
	return _c
}

func (_c *RepoProvider_SelectBalance_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) (balance.UserBalance, error)) *RepoProvider_SelectBalance_Call {
	_c.Call.Return(run)
	return _c
}

// SelectWithdrawals provides a mock function for the type RepoProvider
func (_mock *RepoProvider) SelectWithdrawals(ctx context.Context, userID uuid.UUID) ([]balance.Withdrawal, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for SelectWithdrawals")
	}

	var r0 []balance.Withdrawal
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]balance.Withdrawal, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []balance.Withdrawal); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]balance.Withdrawal)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RepoProvider_SelectWithdrawals_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SelectWithdrawals'
type RepoProvider_SelectWithdrawals_Call struct {
	*mock.Call
}

// SelectWithdrawals is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *RepoProvider_Expecter) SelectWithdrawals(ctx interface{}, userID interface{}) *RepoProvider_SelectWithdrawals_Call {
	return &RepoProvider_SelectWithdrawals_Call{Call: _e.mock.On("SelectWithdrawals", ctx, userID)}
}

func (_c *RepoProvider_SelectWithdrawals_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *RepoProvider_SelectWithdrawals_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RepoProvider_SelectWithdrawals_Call) Return(withdrawals []balance.Withdrawal, err error) *RepoProvider_SelectWithdrawals_Call {
	_c.Call.Return(withdrawals, err)
	return _c
}

func (_c *RepoProvider_SelectWithdrawals_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) ([]balance.Withdrawal, error)) *RepoProvider_SelectWithdrawals_Call {
	_c.Call.Return(run)
	return _c
}

// WithdrawBalance provides a mock function for the type RepoProvider
func (_mock *RepoProvider) WithdrawBalance(ctx context.Context, userID uuid.UUID, opt balance.WithdrawOpt) error {
	ret := _mock.Called(ctx, userID, opt)

	if len(ret) == 0 {
		panic("no return value specified for WithdrawBalance")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, balance.WithdrawOpt) error); ok {
		r0 = returnFunc(ctx, userID, opt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RepoProvider_WithdrawBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithdrawBalance'
type RepoProvider_WithdrawBalance_Call struct {
	*mock.Call
}

// WithdrawBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - opt balance.WithdrawOpt
func (_e *RepoProvider_Expecter) WithdrawBalance(ctx interface{}, userID interface{}, opt interface{}) *RepoProvider_WithdrawBalance_Call {
	return &RepoProvider_WithdrawBalance_Call{Call: _e.mock.On("WithdrawBalance", ctx, userID, opt)}
}

func (_c *RepoProvider_WithdrawBalance_Call) Run(run func(ctx context.Context, userID uuid.UUID, opt balance.WithdrawOpt)) *RepoProvider_WithdrawBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 balance.WithdrawOpt
		if args[2] != nil {
			arg2 = args[2].(balance.WithdrawOpt)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *RepoProvider_WithdrawBalance_Call) Return(err error) *RepoProvider_WithdrawBalance_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RepoProvider_WithdrawBalance_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, opt balance.WithdrawOpt) error) *RepoProvider_WithdrawBalance_Call {
	_c.Call.Return(run)
	return _c
}
