// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package user_mocks

import (
	"context"

	"github.com/Radiushina/loyalty-system/internal/user"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewServiceProvider creates a new instance of ServiceProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServiceProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *ServiceProvider {
	mock := &ServiceProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ServiceProvider is an autogenerated mock type for the ServiceProvider type
type ServiceProvider struct {
	mock.Mock
}

type ServiceProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *ServiceProvider) EXPECT() *ServiceProvider_Expecter {
	return &ServiceProvider_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function for the type ServiceProvider
func (_mock *ServiceProvider) CreateUser(ctx context.Context, login string, password string) (user.AuthUserRes, error) {
	ret := _mock.Called(ctx, login, password)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 user.AuthUserRes
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (user.AuthUserRes, error)); ok {
		return returnFunc(ctx, login, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) user.AuthUserRes); ok {
		r0 = returnFunc(ctx, login, password)
	} else {
		r0 = ret.Get(0).(user.AuthUserRes)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, login, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ServiceProvider_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type ServiceProvider_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - login string
//   - password string
func (_e *ServiceProvider_Expecter) CreateUser(ctx interface{}, login interface{}, password interface{}) *ServiceProvider_CreateUser_Call {
	return &ServiceProvider_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, login, password)}
}

func (_c *ServiceProvider_CreateUser_Call) Run(run func(ctx context.Context, login string, password string)) *ServiceProvider_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ServiceProvider_CreateUser_Call) Return(authUserRes user.AuthUserRes, err error) *ServiceProvider_CreateUser_Call {
	_c.Call.Return(authUserRes, err)
	return _c
}

func (_c *ServiceProvider_CreateUser_Call) RunAndReturn(run func(ctx context.Context, login string, password string) (user.AuthUserRes, error)) *ServiceProvider_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetByLogin provides a mock function for the type ServiceProvider
func (_mock *ServiceProvider) GetByLogin(ctx context.Context, login string, password string) (user.AuthUserRes, error) {
	ret := _mock.Called(ctx, login, password)

	if len(ret) == 0 {
		panic("no return value specified for GetByLogin")
	}

	var r0 user.AuthUserRes
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (user.AuthUserRes, error)); ok {
		return returnFunc(ctx, login, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) user.AuthUserRes); ok {
		r0 = returnFunc(ctx, login, password)
	} else {
		r0 = ret.Get(0).(user.AuthUserRes)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, login, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ServiceProvider_GetByLogin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByLogin'
type ServiceProvider_GetByLogin_Call struct {
	*mock.Call
}

// GetByLogin is a helper method to define mock.On call
//   - ctx context.Context
//   - login string
//   - password string
func (_e *ServiceProvider_Expecter) GetByLogin(ctx interface{}, login interface{}, password interface{}) *ServiceProvider_GetByLogin_Call {
	return &ServiceProvider_GetByLogin_Call{Call: _e.mock.On("GetByLogin", ctx, login, password)}
}

func (_c *ServiceProvider_GetByLogin_Call) Run(run func(ctx context.Context, login string, password string)) *ServiceProvider_GetByLogin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ServiceProvider_GetByLogin_Call) Return(authUserRes user.AuthUserRes, err error) *ServiceProvider_GetByLogin_Call {
	_c.Call.Return(authUserRes, err)
	return _c
}

func (_c *ServiceProvider_GetByLogin_Call) RunAndReturn(run func(ctx context.Context, login string, password string) (user.AuthUserRes, error)) *ServiceProvider_GetByLogin_Call {
	_c.Call.Return(run)
	return _c
}

// NewRepoProvider creates a new instance of RepoProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepoProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *RepoProvider {
	mock := &RepoProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// RepoProvider is an autogenerated mock type for the RepoProvider type
type RepoProvider struct {
	mock.Mock
}

type RepoProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *RepoProvider) EXPECT() *RepoProvider_Expecter {
	return &RepoProvider_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function for the type RepoProvider
func (_mock *RepoProvider) CreateUser(ctx context.Context, ogin string, password string) (user.User, error) {
	ret := _mock.Called(ctx, ogin, password)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 user.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (user.User, error)); ok {
		return returnFunc(ctx, ogin, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) user.User); ok {
		r0 = returnFunc(ctx, ogin, password)
	} else {
		r0 = ret.Get(0).(user.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, ogin, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RepoProvider_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type RepoProvider_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - ogin string
//   - password string
func (_e *RepoProvider_Expecter) CreateUser(ctx interface{}, ogin interface{}, password interface{}) *RepoProvider_CreateUser_Call {
	return &RepoProvider_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, ogin, password)}
}

func (_c *RepoProvider_CreateUser_Call) Run(run func(ctx context.Context, ogin string, password string)) *RepoProvider_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *RepoProvider_CreateUser_Call) Return(user1 user.User, err error) *RepoProvider_CreateUser_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *RepoProvider_CreateUser_Call) RunAndReturn(run func(ctx context.Context, ogin string, password string) (user.User, error)) *RepoProvider_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetByLogin provides a mock function for the type RepoProvider
func (_mock *RepoProvider) GetByLogin(ctx context.Context, ogin string, password string) (user.User, error) {
	ret := _mock.Called(ctx, ogin, password)

	if len(ret) == 0 {
		panic("no return value specified for GetByLogin")
	}

	var r0 user.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (user.User, error)); ok {
		return returnFunc(ctx, ogin, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) user.User); ok {
		r0 = returnFunc(ctx, ogin, password)
	} else {
		r0 = ret.Get(0).(user.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, ogin, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RepoProvider_GetByLogin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByLogin'
type RepoProvider_GetByLogin_Call struct {
	*mock.Call
}

// GetByLogin is a helper method to define mock.On call
//   - ctx context.Context
//   - ogin string
//   - password string
func (_e *RepoProvider_Expecter) GetByLogin(ctx interface{}, ogin interface{}, password interface{}) *RepoProvider_GetByLogin_Call {
	return &RepoProvider_GetByLogin_Call{Call: _e.mock.On("GetByLogin", ctx, ogin, password)}
}

func (_c *RepoProvider_GetByLogin_Call) Run(run func(ctx context.Context, ogin string, password string)) *RepoProvider_GetByLogin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *RepoProvider_GetByLogin_Call) Return(user1 user.User, err error) *RepoProvider_GetByLogin_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *RepoProvider_GetByLogin_Call) RunAndReturn(run func(ctx context.Context, ogin string, password string) (user.User, error)) *RepoProvider_GetByLogin_Call {
	_c.Call.Return(run)
	return _c
}

// NewTokenProvider creates a new instance of TokenProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenProvider {
	mock := &TokenProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TokenProvider is an autogenerated mock type for the TokenProvider type
type TokenProvider struct {
	mock.Mock
}

type TokenProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *TokenProvider) EXPECT() *TokenProvider_Expecter {
	return &TokenProvider_Expecter{mock: &_m.Mock}
}

// Generate provides a mock function for the type TokenProvider
func (_mock *TokenProvider) Generate(userID uuid.UUID) (string, error) {
	ret := _mock.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) (string, error)); ok {
		return returnFunc(userID)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) string); ok {
		r0 = returnFunc(userID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = returnFunc(userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TokenProvider_Generate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Generate'
type TokenProvider_Generate_Call struct {
	*mock.Call
}

// Generate is a helper method to define mock.On call
//   - userID uuid.UUID
func (_e *TokenProvider_Expecter) Generate(userID interface{}) *TokenProvider_Generate_Call {
	return &TokenProvider_Generate_Call{Call: _e.mock.On("Generate", userID)}
}

func (_c *TokenProvider_Generate_Call) Run(run func(userID uuid.UUID)) *TokenProvider_Generate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TokenProvider_Generate_Call) Return(s string, err error) *TokenProvider_Generate_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *TokenProvider_Generate_Call) RunAndReturn(run func(userID uuid.UUID) (string, error)) *TokenProvider_Generate_Call {
	_c.Call.Return(run)
	return _c
}
